// <auto-generated />
using System;
using Marketplace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marketplace.Data.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20221004152757_SeedDataMigration")]
    partial class SeedDataMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Marketplace.Models.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Description = "Officiis qui corrupti est dolor dicta voluptatum.",
                            Metadata = "aut",
                            Name = "Generic Metal Bike"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Necessitatibus sed commodi quos nam ad ut.",
                            Metadata = "distinctio",
                            Name = "Handmade Plastic Mouse"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Dicta facilis eum temporibus laborum sit molestiae sint iusto.",
                            Metadata = "cumque",
                            Name = "Handcrafted Cotton Chips"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Temporibus nostrum et necessitatibus.",
                            Metadata = "hic",
                            Name = "Rustic Fresh Keyboard"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Ut magni optio vel soluta eos.",
                            Metadata = "fuga",
                            Name = "Generic Wooden Sausages"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Modi nulla quia.",
                            Metadata = "laudantium",
                            Name = "Unbranded Metal Towels"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Animi pariatur exercitationem quos labore.",
                            Metadata = "officiis",
                            Name = "Refined Frozen Salad"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Hic vero nihil ab at a.",
                            Metadata = "rerum",
                            Name = "Sleek Cotton Towels"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Molestiae ut provident unde consectetur et voluptatum.",
                            Metadata = "aut",
                            Name = "Generic Granite Pizza"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Aut dolores vero voluptatum blanditiis omnis accusantium.",
                            Metadata = "modi",
                            Name = "Unbranded Frozen Table"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Pariatur quisquam qui laborum quo.",
                            Metadata = "ab",
                            Name = "Handmade Soft Sausages"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Voluptates quo perferendis quasi sed consequatur ut.",
                            Metadata = "odio",
                            Name = "Intelligent Rubber Pizza"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Ex pariatur optio dolore laudantium sed ullam.",
                            Metadata = "eaque",
                            Name = "Incredible Soft Chips"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Voluptas est ea et repudiandae ipsam cupiditate totam aut.",
                            Metadata = "voluptates",
                            Name = "Sleek Frozen Bacon"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Sint dolor nihil temporibus minus delectus facere eligendi.",
                            Metadata = "hic",
                            Name = "Handmade Rubber Bike"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Officia sint omnis sit aut sed.",
                            Metadata = "sit",
                            Name = "Unbranded Metal Pizza"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Mollitia nisi unde.",
                            Metadata = "aut",
                            Name = "Tasty Soft Sausages"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Et est non.",
                            Metadata = "enim",
                            Name = "Refined Rubber Sausages"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Et doloribus animi.",
                            Metadata = "perferendis",
                            Name = "Awesome Granite Chair"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Sapiente excepturi in.",
                            Metadata = "alias",
                            Name = "Incredible Granite Bike"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Eligendi et temporibus corporis qui.",
                            Metadata = "et",
                            Name = "Tasty Steel Car"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Cum quis commodi ex voluptatem ea consequuntur consequuntur neque.",
                            Metadata = "facilis",
                            Name = "Ergonomic Wooden Ball"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Sapiente id enim.",
                            Metadata = "aut",
                            Name = "Awesome Steel Mouse"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Omnis repellat ab quo occaecati suscipit repudiandae ipsam.",
                            Metadata = "quas",
                            Name = "Practical Fresh Shoes"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Eius minima voluptatum assumenda mollitia earum.",
                            Metadata = "dignissimos",
                            Name = "Handcrafted Rubber Cheese"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Qui eos id omnis perspiciatis et.",
                            Metadata = "aut",
                            Name = "Small Concrete Bike"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Nostrum doloribus et sapiente optio.",
                            Metadata = "ipsum",
                            Name = "Fantastic Fresh Shoes"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Fuga repellendus fugit eum quo.",
                            Metadata = "ad",
                            Name = "Small Frozen Ball"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Dolor iusto ut.",
                            Metadata = "architecto",
                            Name = "Refined Plastic Keyboard"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Itaque suscipit quas praesentium labore.",
                            Metadata = "voluptatibus",
                            Name = "Gorgeous Granite Towels"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Sed officiis odit natus.",
                            Metadata = "sint",
                            Name = "Fantastic Cotton Chair"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Aut eligendi quis quos velit qui veritatis non neque.",
                            Metadata = "amet",
                            Name = "Ergonomic Metal Keyboard"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Voluptate odit iste est sed eligendi ut.",
                            Metadata = "tempora",
                            Name = "Handmade Frozen Mouse"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Mollitia voluptates tempora voluptas eius mollitia.",
                            Metadata = "ex",
                            Name = "Practical Plastic Pizza"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Aut et nisi quae et.",
                            Metadata = "cum",
                            Name = "Small Plastic Salad"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Fuga molestiae non dignissimos architecto.",
                            Metadata = "dolor",
                            Name = "Ergonomic Fresh Towels"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Et veritatis et vitae soluta non.",
                            Metadata = "quia",
                            Name = "Handcrafted Steel Hat"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Est ea itaque suscipit neque quia et eaque.",
                            Metadata = "et",
                            Name = "Fantastic Granite Mouse"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Voluptate et in neque quis.",
                            Metadata = "laboriosam",
                            Name = "Handmade Cotton Towels"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Et aliquam odit eaque eum ut praesentium labore voluptatibus.",
                            Metadata = "deserunt",
                            Name = "Licensed Rubber Shirt"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Dignissimos soluta iste maiores nobis et.",
                            Metadata = "atque",
                            Name = "Refined Frozen Pizza"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Iste maxime voluptatem perferendis optio dolores adipisci molestias.",
                            Metadata = "dolores",
                            Name = "Rustic Rubber Chicken"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Vero quam ipsa vitae dolore architecto.",
                            Metadata = "ad",
                            Name = "Generic Cotton Cheese"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Et dolor rerum a soluta maiores magni incidunt consequatur dolorem.",
                            Metadata = "dignissimos",
                            Name = "Intelligent Plastic Gloves"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Sapiente reprehenderit in non.",
                            Metadata = "ipsa",
                            Name = "Rustic Cotton Tuna"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Rem dolorum repudiandae.",
                            Metadata = "dolorem",
                            Name = "Gorgeous Frozen Tuna"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Architecto qui officia rerum.",
                            Metadata = "iusto",
                            Name = "Gorgeous Metal Salad"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Omnis officiis est ducimus.",
                            Metadata = "ullam",
                            Name = "Sleek Metal Computer"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Ea cupiditate unde sapiente dolores quaerat voluptatem quo fugiat.",
                            Metadata = "atque",
                            Name = "Awesome Concrete Gloves"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Sed quasi amet maiores quasi id et reprehenderit.",
                            Metadata = "at",
                            Name = "Small Wooden Cheese"
                        });
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishedDt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Seller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Buyer = "Anibal Gaylord",
                            CreatedDt = new DateTime(2022, 10, 4, 1, 37, 27, 765, DateTimeKind.Local).AddTicks(5303),
                            FinishedDt = new DateTime(2022, 10, 4, 1, 45, 33, 140, DateTimeKind.Local).AddTicks(5376),
                            ItemId = 72,
                            Price = 200.79m,
                            Seller = "White - Runolfsdottir",
                            Status = 2
                        },
                        new
                        {
                            Id = 22,
                            Buyer = "Darrel Bechtelar",
                            CreatedDt = new DateTime(2022, 10, 4, 17, 23, 11, 713, DateTimeKind.Local).AddTicks(8578),
                            FinishedDt = new DateTime(2022, 10, 3, 20, 37, 16, 117, DateTimeKind.Local).AddTicks(4856),
                            ItemId = 76,
                            Price = 513.77m,
                            Seller = "Kulas LLC",
                            Status = 4
                        },
                        new
                        {
                            Id = 23,
                            Buyer = "Pietro Grimes",
                            CreatedDt = new DateTime(2022, 10, 3, 21, 21, 55, 311, DateTimeKind.Local).AddTicks(1733),
                            FinishedDt = new DateTime(2022, 10, 4, 3, 38, 37, 982, DateTimeKind.Local).AddTicks(6891),
                            ItemId = 70,
                            Price = 658.81m,
                            Seller = "Klein Inc",
                            Status = 4
                        },
                        new
                        {
                            Id = 24,
                            Buyer = "Judy Ledner",
                            CreatedDt = new DateTime(2022, 10, 4, 4, 25, 27, 878, DateTimeKind.Local).AddTicks(6353),
                            FinishedDt = new DateTime(2022, 10, 4, 17, 4, 35, 78, DateTimeKind.Local).AddTicks(7096),
                            ItemId = 53,
                            Price = 675.98m,
                            Seller = "Halvorson - Streich",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            Buyer = "Adrian Gusikowski",
                            CreatedDt = new DateTime(2022, 10, 4, 5, 1, 38, 641, DateTimeKind.Local).AddTicks(4528),
                            FinishedDt = new DateTime(2022, 10, 4, 4, 57, 21, 39, DateTimeKind.Local).AddTicks(9842),
                            ItemId = 60,
                            Price = 758.52m,
                            Seller = "Bode, Baumbach and Brekke",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            Buyer = "Maynard Ankunding",
                            CreatedDt = new DateTime(2022, 10, 4, 14, 10, 57, 654, DateTimeKind.Local).AddTicks(9018),
                            FinishedDt = new DateTime(2022, 10, 4, 8, 47, 16, 330, DateTimeKind.Local).AddTicks(8277),
                            ItemId = 55,
                            Price = 617.06m,
                            Seller = "Jerde - Keebler",
                            Status = 4
                        },
                        new
                        {
                            Id = 27,
                            Buyer = "Garfield Mills",
                            CreatedDt = new DateTime(2022, 10, 4, 16, 17, 41, 174, DateTimeKind.Local).AddTicks(247),
                            FinishedDt = new DateTime(2022, 10, 3, 22, 58, 40, 190, DateTimeKind.Local).AddTicks(6484),
                            ItemId = 65,
                            Price = 834.88m,
                            Seller = "Greenholt, Heathcote and Reilly",
                            Status = 1
                        },
                        new
                        {
                            Id = 28,
                            Buyer = "Mathias Crona",
                            CreatedDt = new DateTime(2022, 10, 3, 22, 57, 43, 268, DateTimeKind.Local).AddTicks(5978),
                            FinishedDt = new DateTime(2022, 10, 3, 22, 19, 33, 214, DateTimeKind.Local).AddTicks(671),
                            ItemId = 73,
                            Price = 285.18m,
                            Seller = "Bartoletti, Ernser and Cronin",
                            Status = 2
                        },
                        new
                        {
                            Id = 29,
                            Buyer = "Toni Muller",
                            CreatedDt = new DateTime(2022, 10, 4, 6, 31, 56, 235, DateTimeKind.Local).AddTicks(3790),
                            FinishedDt = new DateTime(2022, 10, 4, 10, 46, 43, 294, DateTimeKind.Local).AddTicks(9775),
                            ItemId = 74,
                            Price = 244.30m,
                            Seller = "Donnelly, Moen and Senger",
                            Status = 4
                        },
                        new
                        {
                            Id = 30,
                            Buyer = "August Nienow",
                            CreatedDt = new DateTime(2022, 10, 4, 8, 32, 12, 853, DateTimeKind.Local).AddTicks(9656),
                            FinishedDt = new DateTime(2022, 10, 4, 9, 59, 17, 656, DateTimeKind.Local).AddTicks(1425),
                            ItemId = 70,
                            Price = 596.69m,
                            Seller = "Balistreri and Sons",
                            Status = 1
                        },
                        new
                        {
                            Id = 31,
                            Buyer = "Zoie Ferry",
                            CreatedDt = new DateTime(2022, 10, 3, 23, 12, 28, 389, DateTimeKind.Local).AddTicks(1021),
                            FinishedDt = new DateTime(2022, 10, 4, 7, 39, 9, 814, DateTimeKind.Local).AddTicks(6233),
                            ItemId = 56,
                            Price = 34.07m,
                            Seller = "Kessler LLC",
                            Status = 2
                        },
                        new
                        {
                            Id = 32,
                            Buyer = "Deborah Bechtelar",
                            CreatedDt = new DateTime(2022, 10, 4, 7, 40, 57, 408, DateTimeKind.Local).AddTicks(8166),
                            FinishedDt = new DateTime(2022, 10, 4, 13, 11, 27, 143, DateTimeKind.Local).AddTicks(6335),
                            ItemId = 76,
                            Price = 879.30m,
                            Seller = "Gulgowski LLC",
                            Status = 4
                        },
                        new
                        {
                            Id = 33,
                            Buyer = "Domenic Wolf",
                            CreatedDt = new DateTime(2022, 10, 4, 11, 17, 39, 50, DateTimeKind.Local).AddTicks(5424),
                            FinishedDt = new DateTime(2022, 10, 4, 6, 58, 59, 987, DateTimeKind.Local).AddTicks(8560),
                            ItemId = 74,
                            Price = 498.97m,
                            Seller = "Goldner, Hettinger and Mills",
                            Status = 2
                        },
                        new
                        {
                            Id = 34,
                            Buyer = "Greg Dickinson",
                            CreatedDt = new DateTime(2022, 10, 4, 1, 14, 14, 229, DateTimeKind.Local).AddTicks(9465),
                            FinishedDt = new DateTime(2022, 10, 4, 8, 5, 27, 414, DateTimeKind.Local).AddTicks(1385),
                            ItemId = 62,
                            Price = 124.59m,
                            Seller = "Lubowitz, Breitenberg and Wolf",
                            Status = 1
                        },
                        new
                        {
                            Id = 35,
                            Buyer = "Dave Renner",
                            CreatedDt = new DateTime(2022, 10, 4, 9, 41, 53, 725, DateTimeKind.Local).AddTicks(9725),
                            FinishedDt = new DateTime(2022, 10, 4, 15, 29, 54, 174, DateTimeKind.Local).AddTicks(7794),
                            ItemId = 62,
                            Price = 916.48m,
                            Seller = "McDermott, Leffler and Legros",
                            Status = 2
                        },
                        new
                        {
                            Id = 36,
                            Buyer = "Edd Erdman",
                            CreatedDt = new DateTime(2022, 10, 4, 15, 20, 19, 526, DateTimeKind.Local).AddTicks(4163),
                            FinishedDt = new DateTime(2022, 10, 3, 20, 22, 41, 460, DateTimeKind.Local).AddTicks(2780),
                            ItemId = 78,
                            Price = 905.99m,
                            Seller = "Stehr - Lemke",
                            Status = 1
                        },
                        new
                        {
                            Id = 37,
                            Buyer = "Godfrey Rutherford",
                            CreatedDt = new DateTime(2022, 10, 4, 4, 55, 38, 492, DateTimeKind.Local).AddTicks(3076),
                            FinishedDt = new DateTime(2022, 10, 4, 4, 13, 59, 112, DateTimeKind.Local).AddTicks(908),
                            ItemId = 79,
                            Price = 541.24m,
                            Seller = "Herzog, Considine and Stehr",
                            Status = 1
                        },
                        new
                        {
                            Id = 38,
                            Buyer = "Mekhi Beatty",
                            CreatedDt = new DateTime(2022, 10, 4, 11, 42, 45, 951, DateTimeKind.Local).AddTicks(2337),
                            FinishedDt = new DateTime(2022, 10, 4, 11, 44, 20, 238, DateTimeKind.Local).AddTicks(7034),
                            ItemId = 67,
                            Price = 944.06m,
                            Seller = "Mann Inc",
                            Status = 2
                        },
                        new
                        {
                            Id = 39,
                            Buyer = "Chadrick Gulgowski",
                            CreatedDt = new DateTime(2022, 10, 4, 13, 40, 55, 255, DateTimeKind.Local).AddTicks(3520),
                            FinishedDt = new DateTime(2022, 10, 4, 1, 49, 37, 7, DateTimeKind.Local).AddTicks(5597),
                            ItemId = 63,
                            Price = 47.87m,
                            Seller = "Armstrong Inc",
                            Status = 1
                        },
                        new
                        {
                            Id = 40,
                            Buyer = "Elvis Murazik",
                            CreatedDt = new DateTime(2022, 10, 4, 1, 33, 50, 771, DateTimeKind.Local).AddTicks(8383),
                            FinishedDt = new DateTime(2022, 10, 3, 23, 3, 37, 381, DateTimeKind.Local).AddTicks(2230),
                            ItemId = 66,
                            Price = 555.56m,
                            Seller = "Herzog Inc",
                            Status = 2
                        });
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Sale", b =>
                {
                    b.HasOne("Marketplace.Models.Domain.Item", null)
                        .WithMany("Sales")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Item", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
