// <auto-generated />
using System;
using Marketplace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marketplace.Data.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20221003142013_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Marketplace.Models.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Description = "Natus omnis eius quidem a.",
                            Metadata = "voluptatem",
                            Name = "Licensed Concrete Pants"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Non ea velit consequatur pariatur sapiente sed voluptas et labore.",
                            Metadata = "dolor",
                            Name = "Generic Wooden Soap"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Repellat quo corporis ipsum et.",
                            Metadata = "rerum",
                            Name = "Unbranded Wooden Chips"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Libero expedita qui provident animi rem molestias architecto velit mollitia.",
                            Metadata = "quibusdam",
                            Name = "Intelligent Plastic Ball"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Minima qui natus sunt eius amet consequatur ea recusandae.",
                            Metadata = "porro",
                            Name = "Intelligent Metal Chips"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Voluptatum molestiae velit voluptatem dolorum aspernatur totam.",
                            Metadata = "dicta",
                            Name = "Handmade Metal Pizza"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Repellendus possimus officia inventore officia illo temporibus.",
                            Metadata = "omnis",
                            Name = "Sleek Rubber Pizza"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Aut omnis ut iusto assumenda.",
                            Metadata = "eum",
                            Name = "Small Plastic Bacon"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Sint laudantium explicabo magnam cupiditate quibusdam dolore ad ea in.",
                            Metadata = "et",
                            Name = "Fantastic Cotton Mouse"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Incidunt ad repellendus cupiditate dolore quibusdam.",
                            Metadata = "molestiae",
                            Name = "Licensed Fresh Shoes"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Facere mollitia et quia.",
                            Metadata = "ducimus",
                            Name = "Handmade Wooden Mouse"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Non dolorem reprehenderit autem perferendis qui consectetur cum est.",
                            Metadata = "similique",
                            Name = "Refined Metal Shirt"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Eaque minus delectus.",
                            Metadata = "ab",
                            Name = "Handmade Plastic Tuna"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Sint incidunt delectus.",
                            Metadata = "rem",
                            Name = "Handcrafted Plastic Chips"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Iste velit minus saepe modi.",
                            Metadata = "quae",
                            Name = "Fantastic Steel Shirt"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Officiis sed ipsum tenetur sed tenetur qui quia quia ad.",
                            Metadata = "modi",
                            Name = "Tasty Wooden Towels"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Dolor porro fugit temporibus corporis est quas autem.",
                            Metadata = "est",
                            Name = "Handmade Cotton Hat"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Dolor dolor laboriosam sit ipsam id debitis ducimus rerum placeat.",
                            Metadata = "non",
                            Name = "Tasty Fresh Mouse"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Nihil suscipit labore est adipisci dolores harum natus iste iste.",
                            Metadata = "voluptatem",
                            Name = "Gorgeous Steel Shoes"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Quia et incidunt.",
                            Metadata = "quo",
                            Name = "Gorgeous Concrete Gloves"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Asperiores animi omnis nam rem sint expedita.",
                            Metadata = "deleniti",
                            Name = "Rustic Soft Bacon"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Animi maxime libero.",
                            Metadata = "et",
                            Name = "Practical Steel Chicken"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Vero et aperiam aut nisi est eum consectetur autem.",
                            Metadata = "consequatur",
                            Name = "Unbranded Steel Cheese"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Inventore ut molestiae quo cum quidem similique.",
                            Metadata = "aut",
                            Name = "Licensed Wooden Mouse"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Ut cupiditate blanditiis deserunt qui odit iste.",
                            Metadata = "et",
                            Name = "Handcrafted Soft Hat"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Aut aut vero enim deserunt sit.",
                            Metadata = "dolorem",
                            Name = "Incredible Soft Tuna"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Est provident aut qui ullam et ut modi.",
                            Metadata = "asperiores",
                            Name = "Practical Concrete Shoes"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Quia delectus et atque quaerat.",
                            Metadata = "iusto",
                            Name = "Awesome Metal Table"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Non est laudantium quaerat ipsam vel maxime facilis.",
                            Metadata = "labore",
                            Name = "Gorgeous Concrete Tuna"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Qui sit voluptas veritatis maxime aut modi placeat deserunt.",
                            Metadata = "iure",
                            Name = "Tasty Granite Shirt"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Nulla doloribus vel rerum et est.",
                            Metadata = "aut",
                            Name = "Tasty Concrete Gloves"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Voluptatem corporis delectus laboriosam repellat cupiditate qui possimus quis placeat.",
                            Metadata = "ipsam",
                            Name = "Ergonomic Wooden Fish"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Illo totam illum magnam doloremque optio quis et adipisci accusantium.",
                            Metadata = "sit",
                            Name = "Unbranded Metal Table"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Voluptas temporibus molestias vel velit.",
                            Metadata = "et",
                            Name = "Licensed Frozen Ball"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Minus sit est quo quidem beatae.",
                            Metadata = "quaerat",
                            Name = "Unbranded Rubber Bacon"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Accusamus voluptate natus sapiente labore deleniti accusantium perspiciatis enim.",
                            Metadata = "adipisci",
                            Name = "Ergonomic Soft Towels"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Tempora et et ab amet.",
                            Metadata = "delectus",
                            Name = "Rustic Wooden Sausages"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Facilis eius necessitatibus necessitatibus dolor.",
                            Metadata = "quia",
                            Name = "Sleek Cotton Fish"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Adipisci quaerat tempore unde.",
                            Metadata = "sequi",
                            Name = "Tasty Cotton Table"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Rem amet autem occaecati non et accusamus.",
                            Metadata = "qui",
                            Name = "Sleek Cotton Sausages"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Tempora quis quae ratione accusantium ipsa consectetur cupiditate.",
                            Metadata = "labore",
                            Name = "Practical Soft Bacon"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Illo mollitia pariatur.",
                            Metadata = "eligendi",
                            Name = "Gorgeous Granite Pants"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Veniam fugit id consequatur sed optio ad adipisci aperiam.",
                            Metadata = "et",
                            Name = "Handcrafted Plastic Tuna"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Aut quo neque ipsa incidunt.",
                            Metadata = "nihil",
                            Name = "Fantastic Plastic Table"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Sequi saepe illum velit.",
                            Metadata = "eos",
                            Name = "Generic Soft Gloves"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Aut nemo in sed ipsum aut veritatis consectetur occaecati.",
                            Metadata = "voluptates",
                            Name = "Incredible Steel Soap"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Et explicabo temporibus.",
                            Metadata = "sit",
                            Name = "Small Wooden Car"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Voluptas dolorem quibusdam recusandae quas voluptatem quis occaecati aspernatur.",
                            Metadata = "repellat",
                            Name = "Small Soft Soap"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Odit repellendus ad corporis omnis.",
                            Metadata = "rerum",
                            Name = "Sleek Rubber Tuna"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Et velit tempore quis asperiores sint suscipit ea rerum alias.",
                            Metadata = "voluptates",
                            Name = "Ergonomic Frozen Bacon"
                        });
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishedDt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Seller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Sale", b =>
                {
                    b.HasOne("Marketplace.Models.Domain.Item", null)
                        .WithMany("Sales")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Item", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
