// <auto-generated />
using System;
using Marketplace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marketplace.Data.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20221003142509_SeedSalesMigration")]
    partial class SeedSalesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Marketplace.Models.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Description = "Nihil qui ea dolore minus.",
                            Metadata = "ea",
                            Name = "Unbranded Plastic Shoes"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Incidunt sed culpa rerum adipisci ut omnis accusamus delectus.",
                            Metadata = "numquam",
                            Name = "Sleek Steel Chair"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Quasi delectus nisi quis et.",
                            Metadata = "velit",
                            Name = "Fantastic Granite Salad"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Libero harum necessitatibus officia consequuntur nostrum voluptates quidem.",
                            Metadata = "dolor",
                            Name = "Sleek Wooden Chair"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Perferendis aliquam ea quis debitis.",
                            Metadata = "nam",
                            Name = "Awesome Wooden Computer"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Error provident magni est.",
                            Metadata = "nisi",
                            Name = "Small Concrete Gloves"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Consequatur eaque nisi soluta laudantium.",
                            Metadata = "totam",
                            Name = "Incredible Plastic Table"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Vero sint commodi eum aut laborum.",
                            Metadata = "qui",
                            Name = "Practical Soft Soap"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Explicabo eos nostrum nulla molestiae quaerat.",
                            Metadata = "reiciendis",
                            Name = "Fantastic Steel Chicken"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Sit debitis et qui enim nobis non laborum qui ipsa.",
                            Metadata = "id",
                            Name = "Practical Wooden Chips"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Commodi est consequuntur.",
                            Metadata = "sed",
                            Name = "Sleek Frozen Shirt"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Quas commodi ratione rerum.",
                            Metadata = "reiciendis",
                            Name = "Rustic Plastic Chips"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Nobis est in.",
                            Metadata = "cupiditate",
                            Name = "Gorgeous Rubber Mouse"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Et tempore neque deserunt.",
                            Metadata = "magnam",
                            Name = "Tasty Steel Table"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Ipsam eaque ut.",
                            Metadata = "nihil",
                            Name = "Licensed Cotton Car"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Labore odio expedita dolorem.",
                            Metadata = "ullam",
                            Name = "Gorgeous Fresh Mouse"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Doloremque et et aut dolores debitis amet sed eos est.",
                            Metadata = "et",
                            Name = "Small Granite Tuna"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Aut veritatis soluta.",
                            Metadata = "quaerat",
                            Name = "Intelligent Frozen Salad"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Qui rerum molestias quam ipsum tempora.",
                            Metadata = "laudantium",
                            Name = "Generic Granite Soap"
                        },
                        new
                        {
                            Id = 70,
                            Description = "At illum est numquam impedit quidem sit dolores molestiae.",
                            Metadata = "atque",
                            Name = "Small Metal Pants"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Sed quidem ratione nemo facere occaecati rem pariatur.",
                            Metadata = "est",
                            Name = "Intelligent Cotton Salad"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Nostrum maiores officia ut aperiam odit dolorum id cumque minima.",
                            Metadata = "ut",
                            Name = "Intelligent Metal Gloves"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Amet exercitationem quos expedita perferendis.",
                            Metadata = "rerum",
                            Name = "Unbranded Cotton Chair"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Architecto dolores sed repellendus sed.",
                            Metadata = "beatae",
                            Name = "Awesome Metal Pizza"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Porro aut dolorum sapiente.",
                            Metadata = "beatae",
                            Name = "Rustic Rubber Mouse"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Explicabo quo enim dolor eos.",
                            Metadata = "ut",
                            Name = "Handcrafted Soft Cheese"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Distinctio cumque itaque rerum.",
                            Metadata = "autem",
                            Name = "Handcrafted Wooden Chips"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Vel fugiat sint hic velit adipisci.",
                            Metadata = "voluptas",
                            Name = "Licensed Soft Mouse"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Et corporis praesentium.",
                            Metadata = "exercitationem",
                            Name = "Rustic Cotton Pizza"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Quia velit eos hic.",
                            Metadata = "et",
                            Name = "Unbranded Steel Hat"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Dolores consequuntur tempora molestiae tenetur ipsum et veniam autem.",
                            Metadata = "illo",
                            Name = "Generic Soft Soap"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Deleniti accusantium soluta delectus amet.",
                            Metadata = "accusantium",
                            Name = "Rustic Granite Towels"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Officiis enim dolores aut dolorem omnis eaque eveniet unde.",
                            Metadata = "quaerat",
                            Name = "Awesome Concrete Hat"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Consequatur praesentium natus error vel eum neque totam.",
                            Metadata = "ipsum",
                            Name = "Tasty Fresh Pizza"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Fugiat omnis est suscipit et vitae et dolorum.",
                            Metadata = "aspernatur",
                            Name = "Licensed Wooden Pizza"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Consequatur reiciendis natus fuga.",
                            Metadata = "qui",
                            Name = "Tasty Rubber Keyboard"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Placeat exercitationem dolorem similique ea quo fugiat.",
                            Metadata = "et",
                            Name = "Awesome Wooden Cheese"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Qui ullam nobis ullam fugiat.",
                            Metadata = "voluptatem",
                            Name = "Generic Cotton Computer"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Qui eos delectus iste et est libero ut quia voluptatem.",
                            Metadata = "tempora",
                            Name = "Unbranded Soft Hat"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Nam sed quibusdam id blanditiis modi itaque ad nam.",
                            Metadata = "molestiae",
                            Name = "Generic Rubber Sausages"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Accusantium facere ea et ut tempore officia consequuntur sunt rerum.",
                            Metadata = "alias",
                            Name = "Ergonomic Soft Chicken"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Et quos nam adipisci magni ea quia.",
                            Metadata = "corporis",
                            Name = "Gorgeous Wooden Bike"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Asperiores qui voluptas.",
                            Metadata = "inventore",
                            Name = "Fantastic Granite Towels"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Quis qui dicta in molestias eos.",
                            Metadata = "dolores",
                            Name = "Small Fresh Fish"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Repellendus enim culpa sed ducimus dignissimos maxime distinctio.",
                            Metadata = "eos",
                            Name = "Handmade Metal Chips"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Vero aut a sunt sint dolor voluptates.",
                            Metadata = "aliquam",
                            Name = "Sleek Metal Bike"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Sed enim nemo odio dolor nobis alias velit dolorem quas.",
                            Metadata = "libero",
                            Name = "Rustic Rubber Pizza"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Quas quis pariatur a pariatur asperiores ut.",
                            Metadata = "aut",
                            Name = "Intelligent Granite Gloves"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Temporibus mollitia repellendus ducimus doloribus maiores consequatur dolores eius.",
                            Metadata = "animi",
                            Name = "Refined Wooden Towels"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Ut molestiae numquam minima vel laboriosam praesentium.",
                            Metadata = "sit",
                            Name = "Awesome Soft Cheese"
                        });
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishedDt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Seller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Buyer = "Tierra Ratke",
                            CreatedDt = new DateTime(3635, 8, 14, 18, 38, 43, 482, DateTimeKind.Unspecified).AddTicks(5984),
                            FinishedDt = new DateTime(5887, 3, 6, 1, 50, 23, 563, DateTimeKind.Unspecified).AddTicks(5456),
                            ItemId = 58,
                            Price = 742.08m,
                            Seller = "Heathcote, Schoen and Stiedemann",
                            Status = 2
                        },
                        new
                        {
                            Id = 22,
                            Buyer = "Maximo Keeling",
                            CreatedDt = new DateTime(8309, 11, 23, 2, 15, 42, 586, DateTimeKind.Unspecified).AddTicks(3168),
                            FinishedDt = new DateTime(6150, 7, 25, 22, 53, 34, 317, DateTimeKind.Unspecified).AddTicks(4912),
                            ItemId = 57,
                            Price = 283.75m,
                            Seller = "Miller Inc",
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            Buyer = "Merl Bednar",
                            CreatedDt = new DateTime(9267, 3, 31, 10, 8, 55, 448, DateTimeKind.Unspecified).AddTicks(8320),
                            FinishedDt = new DateTime(559, 4, 6, 13, 44, 12, 118, DateTimeKind.Unspecified).AddTicks(6624),
                            ItemId = 61,
                            Price = 500.80m,
                            Seller = "Nienow, Bayer and Volkman",
                            Status = 3
                        },
                        new
                        {
                            Id = 24,
                            Buyer = "Raymond Hettinger",
                            CreatedDt = new DateTime(816, 9, 25, 6, 51, 32, 673, DateTimeKind.Unspecified).AddTicks(8720),
                            FinishedDt = new DateTime(703, 3, 4, 22, 58, 58, 829, DateTimeKind.Unspecified).AddTicks(8880),
                            ItemId = 55,
                            Price = 433.05m,
                            Seller = "Effertz, Reichel and Murray",
                            Status = 3
                        },
                        new
                        {
                            Id = 25,
                            Buyer = "Ayla Lueilwitz",
                            CreatedDt = new DateTime(9986, 1, 31, 15, 49, 46, 728, DateTimeKind.Unspecified).AddTicks(896),
                            FinishedDt = new DateTime(8630, 2, 2, 12, 47, 40, 293, DateTimeKind.Unspecified).AddTicks(7856),
                            ItemId = 60,
                            Price = 565.37m,
                            Seller = "Erdman Inc",
                            Status = 3
                        },
                        new
                        {
                            Id = 26,
                            Buyer = "Petra Sporer",
                            CreatedDt = new DateTime(4388, 12, 9, 0, 34, 55, 535, DateTimeKind.Unspecified).AddTicks(528),
                            FinishedDt = new DateTime(9185, 10, 13, 15, 29, 36, 915, DateTimeKind.Unspecified).AddTicks(8656),
                            ItemId = 58,
                            Price = 589.86m,
                            Seller = "Denesik, Berge and Haag",
                            Status = 2
                        },
                        new
                        {
                            Id = 27,
                            Buyer = "Kim Kunde",
                            CreatedDt = new DateTime(9852, 9, 9, 0, 51, 2, 762, DateTimeKind.Unspecified).AddTicks(9568),
                            FinishedDt = new DateTime(813, 1, 11, 17, 20, 58, 993, DateTimeKind.Unspecified).AddTicks(9200),
                            ItemId = 57,
                            Price = 479.26m,
                            Seller = "Russel - Schneider",
                            Status = 3
                        },
                        new
                        {
                            Id = 28,
                            Buyer = "Dion Krajcik",
                            CreatedDt = new DateTime(9250, 5, 3, 17, 14, 30, 371, DateTimeKind.Unspecified).AddTicks(2256),
                            FinishedDt = new DateTime(2428, 7, 5, 16, 21, 6, 188, DateTimeKind.Unspecified).AddTicks(3904),
                            ItemId = 52,
                            Price = 704.09m,
                            Seller = "Mayert - Lubowitz",
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            Buyer = "Elenor Goyette",
                            CreatedDt = new DateTime(8916, 8, 9, 9, 3, 29, 92, DateTimeKind.Unspecified).AddTicks(5568),
                            FinishedDt = new DateTime(3583, 1, 28, 8, 8, 11, 302, DateTimeKind.Unspecified).AddTicks(5792),
                            ItemId = 60,
                            Price = 221.41m,
                            Seller = "Bergstrom LLC",
                            Status = 2
                        },
                        new
                        {
                            Id = 30,
                            Buyer = "Joana Spinka",
                            CreatedDt = new DateTime(2429, 9, 13, 4, 56, 15, 346, DateTimeKind.Unspecified).AddTicks(4192),
                            FinishedDt = new DateTime(650, 12, 13, 14, 45, 34, 946, DateTimeKind.Unspecified).AddTicks(7040),
                            ItemId = 57,
                            Price = 264.57m,
                            Seller = "Crist, Ortiz and Brakus",
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            Buyer = "Kolby Pollich",
                            CreatedDt = new DateTime(351, 8, 14, 3, 37, 51, 694, DateTimeKind.Unspecified).AddTicks(368),
                            FinishedDt = new DateTime(6897, 10, 27, 4, 8, 40, 658, DateTimeKind.Unspecified).AddTicks(224),
                            ItemId = 53,
                            Price = 472.42m,
                            Seller = "Wyman, Stracke and O'Hara",
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            Buyer = "Edmund Corkery",
                            CreatedDt = new DateTime(8002, 5, 20, 23, 52, 38, 30, DateTimeKind.Unspecified).AddTicks(1824),
                            FinishedDt = new DateTime(4225, 8, 29, 1, 37, 36, 748, DateTimeKind.Unspecified).AddTicks(64),
                            ItemId = 54,
                            Price = 552.10m,
                            Seller = "Schiller and Sons",
                            Status = 1
                        },
                        new
                        {
                            Id = 33,
                            Buyer = "Darren Feest",
                            CreatedDt = new DateTime(2761, 2, 7, 2, 29, 52, 188, DateTimeKind.Unspecified).AddTicks(3392),
                            FinishedDt = new DateTime(8849, 3, 29, 18, 47, 19, 783, DateTimeKind.Unspecified).AddTicks(6800),
                            ItemId = 59,
                            Price = 642.30m,
                            Seller = "Glover and Sons",
                            Status = 1
                        },
                        new
                        {
                            Id = 34,
                            Buyer = "Jaleel Wuckert",
                            CreatedDt = new DateTime(97, 10, 26, 2, 28, 20, 329, DateTimeKind.Unspecified).AddTicks(7348),
                            FinishedDt = new DateTime(3277, 7, 13, 4, 57, 18, 268, DateTimeKind.Unspecified).AddTicks(6592),
                            ItemId = 60,
                            Price = 501.94m,
                            Seller = "Miller Inc",
                            Status = 3
                        },
                        new
                        {
                            Id = 35,
                            Buyer = "Davin Rolfson",
                            CreatedDt = new DateTime(2628, 1, 3, 9, 51, 59, 952, DateTimeKind.Unspecified).AddTicks(9728),
                            FinishedDt = new DateTime(4105, 3, 22, 14, 40, 5, 820, DateTimeKind.Unspecified).AddTicks(8768),
                            ItemId = 51,
                            Price = 627.08m,
                            Seller = "Moen - Satterfield",
                            Status = 3
                        },
                        new
                        {
                            Id = 36,
                            Buyer = "Lawson Feest",
                            CreatedDt = new DateTime(9144, 10, 7, 22, 28, 33, 289, DateTimeKind.Unspecified).AddTicks(1648),
                            FinishedDt = new DateTime(9129, 8, 9, 18, 38, 29, 122, DateTimeKind.Unspecified).AddTicks(2016),
                            ItemId = 54,
                            Price = 874.58m,
                            Seller = "Sauer - Bruen",
                            Status = 3
                        },
                        new
                        {
                            Id = 37,
                            Buyer = "Domenica Wilderman",
                            CreatedDt = new DateTime(9411, 10, 9, 1, 46, 30, 429, DateTimeKind.Unspecified).AddTicks(7472),
                            FinishedDt = new DateTime(6827, 7, 30, 22, 57, 50, 216, DateTimeKind.Unspecified).AddTicks(8832),
                            ItemId = 51,
                            Price = 120.64m,
                            Seller = "Brown - Weissnat",
                            Status = 3
                        },
                        new
                        {
                            Id = 38,
                            Buyer = "Jedediah Sipes",
                            CreatedDt = new DateTime(3643, 2, 10, 16, 48, 15, 591, DateTimeKind.Unspecified).AddTicks(8080),
                            FinishedDt = new DateTime(8329, 1, 7, 5, 32, 43, 807, DateTimeKind.Unspecified).AddTicks(7952),
                            ItemId = 56,
                            Price = 636.04m,
                            Seller = "Cassin Inc",
                            Status = 2
                        },
                        new
                        {
                            Id = 39,
                            Buyer = "Winston Ebert",
                            CreatedDt = new DateTime(2258, 3, 10, 13, 43, 58, 533, DateTimeKind.Unspecified).AddTicks(3120),
                            FinishedDt = new DateTime(4545, 3, 12, 10, 14, 2, 766, DateTimeKind.Unspecified).AddTicks(8992),
                            ItemId = 60,
                            Price = 707.88m,
                            Seller = "Ebert and Sons",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            Buyer = "Vaughn O'Reilly",
                            CreatedDt = new DateTime(3813, 3, 30, 10, 26, 53, 903, DateTimeKind.Unspecified).AddTicks(8208),
                            FinishedDt = new DateTime(7300, 12, 23, 21, 27, 13, 777, DateTimeKind.Unspecified).AddTicks(2544),
                            ItemId = 59,
                            Price = 650.57m,
                            Seller = "Kihn, Kunze and Waters",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Sale", b =>
                {
                    b.HasOne("Marketplace.Models.Domain.Item", null)
                        .WithMany("Sales")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Models.Domain.Item", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
